debug: false
server:
   port: 8780
spring:
   application:
      name: hexie-config-center
   cloud: 
      config:
         server: 
            native:  
               searchLocations: classpath:/config   #读配置文件的地方，也可以是某个git或者svn地址
eureka:
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://hexie:hexie231@localhost:8761/eureka/   #eureka地址
   instance:
      hostname: ${spring.cloud.client.ipAddress}
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}   #实例id
      prefer-ip-address : false   #注册IP还是主机名，true就ip
