debug: false
server:
   port: 8780
spring:
   profiles: 
      active: native   #设置使用本地配置(默认是git,可以设置：subversion(SVN)，native(本地))
   application:
      name: hexie-config-server
   cloud: 
      config:
         server: 
            native:  
               searchLocations: classpath:/config
eureka:
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://hexie:hexie231@localhost:8761/eureka/
   instance:
      hostname: ${spring.cloud.client.ipAddress}
      instance-id: ${spring.cloud.client.ipAddress}:${spring.cloud.client.hostname}:${server.port}
      prefer-ip-address : false

security:
    basic:
        enabled: true
    user:
        name: hexie
        password: hexie232
        
info:   
   app: 
      name: config-server
   company:
      name: www.e-shequ.cn
   build: 
      artifactId: hexie-config
      version: ${project.version}